name: Deploy API Node.js to o2switch

on:
  push:
    branches:
      - fix/yy/ReviewArchiOfProject

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build API
        run: npm run build:api

      #- name: Copy .env file (optionnel, si tu veux versionner un .env.example)
      #  run: cp apps/api/.env dist/apps/api/.env
      
      - name: Deploy to o2switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/apps/api
          server-dir: /www/api # adapte ce chemin à la racine de ton hébergement

      # (Optional) restart node js if needed
      # - name: Restart Node.js app via SSH
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASS }}
      #     script: |
      #       cd /www/api
      #       pm2 restart all
