name: Deploy API to o2switch

on:
  push:
    branches:
      - main
# on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build API and Frontend
        run: npm run build:prod

      - name: Copy .htaccess to frontend dist
        run: cp scripts/.htaccess dist/apps/frontend/.htaccess

      #- name: Copy .env file (optionnel, si tu veux versionner un .env.example)
      #  run: cp apps/api/.env dist/apps/api/.env
      
      - name: Deploy API via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/apps/api/
          dangerous-clean-slate: true
 
      # - name: Restart Node.js app via SSH
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASS }}
      #     script: |
      #       cd /www/api
      #       pm2 restart all

      - name: Deploy Frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_FRONT_SERVER }}
          username: ${{ secrets.FTP_FRONT_USERNAME }}
          password: ${{ secrets.FTP_FRONT_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: dist/apps/frontend/
          dangerous-clean-slate: true
       

